#!/bin/bash
##SBATCH -A see180004p # 2021 Allocation -- This might change in the following years.
#SBATCH -J particle-gpu
#SBATCH -o particle-gpu.stdout
#SBATCH -n 1         
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:1
#SBATCH -t 00:10:00

./gpu -n 2000 -o gpu.txt
./autocorrect -s gpu.txt
