#!/bin/bash
##SBATCH -A see180004p # 2021 Allocation -- This might change in the following years.
#SBATCH -J particle-serial
#SBATCH -o particle-serial.stdout
#SBATCH -N 1         
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:1
#SBATCH -t 00:10:00

./serial -n 2000 -o serial.txt
./autocorrect -s serial.txt
